// tslint:disable
/**
 * FlowAccount Business API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    Company,
    ExpenseCategory,
} from './';

/**
 * @export
 * @interface CompanyExpenseCategory
 */
export interface CompanyExpenseCategory {
    /**
     * @type {number}
     * @memberof CompanyExpenseCategory
     */
    companyId?: number;
    /**
     * @type {number}
     * @memberof CompanyExpenseCategory
     */
    expenseCategoryId?: number;
    /**
     * @type {Company}
     * @memberof CompanyExpenseCategory
     */
    company?: Company | null;
    /**
     * @type {ExpenseCategory}
     * @memberof CompanyExpenseCategory
     */
    expenseCategory?: ExpenseCategory | null;
}
