// tslint:disable
/**
 * FlowAccount Business API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum DocumentTemplates {
    NUMBER_1 = 1,
    NUMBER_3 = 3,
    NUMBER_5 = 5,
    NUMBER_7 = 7,
    NUMBER_9 = 9,
    NUMBER_11 = 11,
    NUMBER_13 = 13,
    NUMBER_15 = 15,
    NUMBER_17 = 17,
    NUMBER_101 = 101,
    NUMBER_103 = 103,
    NUMBER_105 = 105,
    NUMBER_107 = 107,
    NUMBER_109 = 109,
    NUMBER_111 = 111,
    NUMBER_113 = 113,
    NUMBER_115 = 115,
    NUMBER_201 = 201,
    NUMBER_203 = 203,
    NUMBER_205 = 205,
    NUMBER_301 = 301,
    NUMBER_303 = 303,
    NUMBER_305 = 305
}

