// tslint:disable
/**
 * FlowAccount Business API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PayrollStatus {
    NUMBER_0 = 0,
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_7 = 7,
    NUMBER_11 = 11,
    NUMBER_13 = 13,
    NUMBER_15 = 15,
    NUMBER_17 = 17,
    NUMBER_19 = 19,
    NUMBER_50 = 50,
    NUMBER_52 = 52,
    NUMBER_54 = 54,
    NUMBER_56 = 56
}

