// tslint:disable
/**
 * FlowAccount Business API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum RemainingCollectedType {
    NUMBER_1 = 1,
    NUMBER_3 = 3,
    NUMBER_51 = 51,
    NUMBER_53 = 53,
    NUMBER_55 = 55,
    NUMBER_57 = 57
}

