// tslint:disable
/**
 * FlowAccount Business API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    BaseDocumentSource,
    Contact,
    ContactGroups,
    CreditTypes,
    Currency,
    DeductionType,
    DepositDocumentType,
    DocumentReference,
    ExpenseCategory,
    ExpenseCategoryViewTypes,
    Gallery,
    Media,
    PartialPaymentMethod,
    ProductDiscountTypes,
    ProductItem2,
    SourceDocumentAllOf,
    TupleOfIDocumentAndIMongoDocument,
} from './';

/**
 * @type SourceDocument
 * @export
 */
export type SourceDocument = BaseDocumentSource & SourceDocumentAllOf;
