=begin
#FlowAccount Open API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module OpenapiClient
  class CompanyTypeEnum
    N10 = 10.freeze
    N20 = 20.freeze
    N30 = 30.freeze
    N40 = 40.freeze
    N50 = 50.freeze
    N60 = 60.freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = CompanyTypeEnum.constants.select { |c| CompanyTypeEnum::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #CompanyTypeEnum" if constantValues.empty?
      value
    end
  end
end
