<?php
/**
 * DocumentTypesTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FlowAccount Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DocumentTypesTest Class Doc Comment
 *
 * @category    Class
 * @description 1 &#x3D; PurchaseOrder 3 &#x3D; Quotation 5 &#x3D; BillingNote 7 &#x3D; TaxInvoice 9 &#x3D; Receipt 13 &#x3D; Expense 15 &#x3D; Vendor 17 &#x3D; WithHoldingTax 19 &#x3D; BillingNotePartials 21 &#x3D; TaxInvoicePartails 23 &#x3D; Purchase 24 &#x3D; PurchaseTax 25 &#x3D; ReceivableInvoice 29 &#x3D; AdjustInventory 31 &#x3D; CreditNote 33 &#x3D; DebitNote 35 &#x3D; CashInvoice 37 &#x3D; PaymentSlip 51 &#x3D; JournalEntry 53 &#x3D; PurchaseVoucher 55 &#x3D; SalesVoucher 57 &#x3D; PaymentVoucher 59 &#x3D; ReceivedVoucher 61 &#x3D; ConversionBalance 63 &#x3D; Transaction 65 &#x3D; SupplierInvoice 67 &#x3D; BatchTaxFiling 69 &#x3D; FixedAsset 71 &#x3D; Depreciation 73 &#x3D; BankTransfer 151 &#x3D; DraftJournalEntry 153 &#x3D; DraftPurchaseVoucher 155 &#x3D; DraftSalesVoucher 157 &#x3D; DraftPaymentVoucher 159 &#x3D; DraftReceivedVoucher 201 &#x3D; Payroll 202 &#x3D; PayrollDetail 203 &#x3D; Employee 204 &#x3D; PayrollPayment
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DocumentTypesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DocumentTypes"
     */
    public function testDocumentTypes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
