=begin
#FlowAccount Open API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::Currency
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::Currency do
  let(:instance) { OpenapiClient::Currency.new }

  describe 'test an instance of Currency' do
    it 'should create an instance of Currency' do
      expect(instance).to be_instance_of(OpenapiClient::Currency)
    end
  end
end
