/*
 * FlowAccount Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BatchMessageStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchMessageStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchMessageStatus
        //private BatchMessageStatus instance;

        public BatchMessageStatusTests()
        {
            // TODO uncomment below to create an instance of BatchMessageStatus
            //instance = new BatchMessageStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchMessageStatus
        /// </summary>
        [Fact]
        public void BatchMessageStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" BatchMessageStatus
            //Assert.IsType<BatchMessageStatus>(instance);
        }


        /// <summary>
        /// Test the property 'CompanyUserGuid'
        /// </summary>
        [Fact]
        public void CompanyUserGuidTest()
        {
            // TODO unit test for the property 'CompanyUserGuid'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'BatchId'
        /// </summary>
        [Fact]
        public void BatchIdTest()
        {
            // TODO unit test for the property 'BatchId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'MessageId'
        /// </summary>
        [Fact]
        public void MessageIdTest()
        {
            // TODO unit test for the property 'MessageId'
        }
        /// <summary>
        /// Test the property 'FailedReason'
        /// </summary>
        [Fact]
        public void FailedReasonTest()
        {
            // TODO unit test for the property 'FailedReason'
        }
        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }
        /// <summary>
        /// Test the property 'RetryCount'
        /// </summary>
        [Fact]
        public void RetryCountTest()
        {
            // TODO unit test for the property 'RetryCount'
        }
        /// <summary>
        /// Test the property 'DocumentSerial'
        /// </summary>
        [Fact]
        public void DocumentSerialTest()
        {
            // TODO unit test for the property 'DocumentSerial'
        }
        /// <summary>
        /// Test the property 'SqlId'
        /// </summary>
        [Fact]
        public void SqlIdTest()
        {
            // TODO unit test for the property 'SqlId'
        }
        /// <summary>
        /// Test the property 'RowIndex'
        /// </summary>
        [Fact]
        public void RowIndexTest()
        {
            // TODO unit test for the property 'RowIndex'
        }

    }

}
