/*
 * FlowAccount Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing BatchHistory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BatchHistoryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BatchHistory
        //private BatchHistory instance;

        public BatchHistoryTests()
        {
            // TODO uncomment below to create an instance of BatchHistory
            //instance = new BatchHistory();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BatchHistory
        /// </summary>
        [Fact]
        public void BatchHistoryInstanceTest()
        {
            // TODO uncomment below to test "IsType" BatchHistory
            //Assert.IsType<BatchHistory>(instance);
        }


        /// <summary>
        /// Test the property 'MetadataList'
        /// </summary>
        [Fact]
        public void MetadataListTest()
        {
            // TODO unit test for the property 'MetadataList'
        }

    }

}
