/*
 * FlowAccount Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentQuery
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentQueryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentQuery
        //private DocumentQuery instance;

        public DocumentQueryTests()
        {
            // TODO uncomment below to create an instance of DocumentQuery
            //instance = new DocumentQuery();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentQuery
        /// </summary>
        [Fact]
        public void DocumentQueryInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentQuery
            //Assert.IsType<DocumentQuery>(instance);
        }


        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
        /// <summary>
        /// Test the property 'CurrentPage'
        /// </summary>
        [Fact]
        public void CurrentPageTest()
        {
            // TODO unit test for the property 'CurrentPage'
        }
        /// <summary>
        /// Test the property 'TotalRecords'
        /// </summary>
        [Fact]
        public void TotalRecordsTest()
        {
            // TODO unit test for the property 'TotalRecords'
        }
        /// <summary>
        /// Test the property 'DateType'
        /// </summary>
        [Fact]
        public void DateTypeTest()
        {
            // TODO unit test for the property 'DateType'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Fact]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Fact]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'Day'
        /// </summary>
        [Fact]
        public void DayTest()
        {
            // TODO unit test for the property 'Day'
        }
        /// <summary>
        /// Test the property 'Month'
        /// </summary>
        [Fact]
        public void MonthTest()
        {
            // TODO unit test for the property 'Month'
        }
        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Fact]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
        /// <summary>
        /// Test the property 'Range'
        /// </summary>
        [Fact]
        public void RangeTest()
        {
            // TODO unit test for the property 'Range'
        }
        /// <summary>
        /// Test the property 'IsFirstCurrent'
        /// </summary>
        [Fact]
        public void IsFirstCurrentTest()
        {
            // TODO unit test for the property 'IsFirstCurrent'
        }
        /// <summary>
        /// Test the property 'HashTags'
        /// </summary>
        [Fact]
        public void HashTagsTest()
        {
            // TODO unit test for the property 'HashTags'
        }
        /// <summary>
        /// Test the property 'ReportType'
        /// </summary>
        [Fact]
        public void ReportTypeTest()
        {
            // TODO unit test for the property 'ReportType'
        }
        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }
        /// <summary>
        /// Test the property 'SortBy'
        /// </summary>
        [Fact]
        public void SortByTest()
        {
            // TODO unit test for the property 'SortBy'
        }
        /// <summary>
        /// Test the property 'TotalValue'
        /// </summary>
        [Fact]
        public void TotalValueTest()
        {
            // TODO unit test for the property 'TotalValue'
        }
        /// <summary>
        /// Test the property 'TotalVAT'
        /// </summary>
        [Fact]
        public void TotalVATTest()
        {
            // TODO unit test for the property 'TotalVAT'
        }
        /// <summary>
        /// Test the property 'IsReceived'
        /// </summary>
        [Fact]
        public void IsReceivedTest()
        {
            // TODO unit test for the property 'IsReceived'
        }
        /// <summary>
        /// Test the property 'DocumentType'
        /// </summary>
        [Fact]
        public void DocumentTypeTest()
        {
            // TODO unit test for the property 'DocumentType'
        }
        /// <summary>
        /// Test the property 'Revenue'
        /// </summary>
        [Fact]
        public void RevenueTest()
        {
            // TODO unit test for the property 'Revenue'
        }
        /// <summary>
        /// Test the property 'Expenses'
        /// </summary>
        [Fact]
        public void ExpensesTest()
        {
            // TODO unit test for the property 'Expenses'
        }
        /// <summary>
        /// Test the property 'PreviousMonths'
        /// </summary>
        [Fact]
        public void PreviousMonthsTest()
        {
            // TODO unit test for the property 'PreviousMonths'
        }
        /// <summary>
        /// Test the property 'PreviousYears'
        /// </summary>
        [Fact]
        public void PreviousYearsTest()
        {
            // TODO unit test for the property 'PreviousYears'
        }
        /// <summary>
        /// Test the property 'CustomDocumentModels'
        /// </summary>
        [Fact]
        public void CustomDocumentModelsTest()
        {
            // TODO unit test for the property 'CustomDocumentModels'
        }

    }

}
