/*
 * FlowAccount Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ExpenseStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExpenseStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExpenseStatus
        //private ExpenseStatus instance;

        public ExpenseStatusTests()
        {
            // TODO uncomment below to create an instance of ExpenseStatus
            //instance = new ExpenseStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExpenseStatus
        /// </summary>
        [Fact]
        public void ExpenseStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExpenseStatus
            //Assert.IsType<ExpenseStatus>(instance);
        }



    }

}
