/*
 * FlowAccount Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Gallery
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GalleryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Gallery
        //private Gallery instance;

        public GalleryTests()
        {
            // TODO uncomment below to create an instance of Gallery
            //instance = new Gallery();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Gallery
        /// </summary>
        [Fact]
        public void GalleryInstanceTest()
        {
            // TODO uncomment below to test "IsType" Gallery
            //Assert.IsType<Gallery>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'ProductList'
        /// </summary>
        [Fact]
        public void ProductListTest()
        {
            // TODO unit test for the property 'ProductList'
        }
        /// <summary>
        /// Test the property 'Media'
        /// </summary>
        [Fact]
        public void MediaTest()
        {
            // TODO unit test for the property 'Media'
        }
        /// <summary>
        /// Test the property 'JournalEntry'
        /// </summary>
        [Fact]
        public void JournalEntryTest()
        {
            // TODO unit test for the property 'JournalEntry'
        }
        /// <summary>
        /// Test the property 'ReceivableInvoice'
        /// </summary>
        [Fact]
        public void ReceivableInvoiceTest()
        {
            // TODO unit test for the property 'ReceivableInvoice'
        }
        /// <summary>
        /// Test the property 'SupplierInvoice'
        /// </summary>
        [Fact]
        public void SupplierInvoiceTest()
        {
            // TODO unit test for the property 'SupplierInvoice'
        }

    }

}
