/*
 * FlowAccount Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OtherChannels
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OtherChannelsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OtherChannels
        //private OtherChannels instance;

        public OtherChannelsTests()
        {
            // TODO uncomment below to create an instance of OtherChannels
            //instance = new OtherChannels();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OtherChannels
        /// </summary>
        [Fact]
        public void OtherChannelsInstanceTest()
        {
            // TODO uncomment below to test "IsType" OtherChannels
            //Assert.IsType<OtherChannels>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CompanyId'
        /// </summary>
        [Fact]
        public void CompanyIdTest()
        {
            // TODO unit test for the property 'CompanyId'
        }
        /// <summary>
        /// Test the property 'ChartOfAccountId'
        /// </summary>
        [Fact]
        public void ChartOfAccountIdTest()
        {
            // TODO unit test for the property 'ChartOfAccountId'
        }
        /// <summary>
        /// Test the property 'ChartOfAccount'
        /// </summary>
        [Fact]
        public void ChartOfAccountTest()
        {
            // TODO unit test for the property 'ChartOfAccount'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Channel'
        /// </summary>
        [Fact]
        public void ChannelTest()
        {
            // TODO unit test for the property 'Channel'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'BankId'
        /// </summary>
        [Fact]
        public void BankIdTest()
        {
            // TODO unit test for the property 'BankId'
        }
        /// <summary>
        /// Test the property 'Bank'
        /// </summary>
        [Fact]
        public void BankTest()
        {
            // TODO unit test for the property 'Bank'
        }
        /// <summary>
        /// Test the property 'BankName'
        /// </summary>
        [Fact]
        public void BankNameTest()
        {
            // TODO unit test for the property 'BankName'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Fact]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'ModifiedOn'
        /// </summary>
        [Fact]
        public void ModifiedOnTest()
        {
            // TODO unit test for the property 'ModifiedOn'
        }
        /// <summary>
        /// Test the property 'IsDelete'
        /// </summary>
        [Fact]
        public void IsDeleteTest()
        {
            // TODO unit test for the property 'IsDelete'
        }

    }

}
