/*
 * FlowAccount Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ProductList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductList
        //private ProductList instance;

        public ProductListTests()
        {
            // TODO uncomment below to create an instance of ProductList
            //instance = new ProductList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductList
        /// </summary>
        [Fact]
        public void ProductListInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductList
            //Assert.IsType<ProductList>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'BarCode'
        /// </summary>
        [Fact]
        public void BarCodeTest()
        {
            // TODO unit test for the property 'BarCode'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'UnitMeasurement'
        /// </summary>
        [Fact]
        public void UnitMeasurementTest()
        {
            // TODO unit test for the property 'UnitMeasurement'
        }
        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Fact]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }
        /// <summary>
        /// Test the property 'UnitPriceWithVat'
        /// </summary>
        [Fact]
        public void UnitPriceWithVatTest()
        {
            // TODO unit test for the property 'UnitPriceWithVat'
        }
        /// <summary>
        /// Test the property 'UnitWeight'
        /// </summary>
        [Fact]
        public void UnitWeightTest()
        {
            // TODO unit test for the property 'UnitWeight'
        }
        /// <summary>
        /// Test the property 'CategoryId'
        /// </summary>
        [Fact]
        public void CategoryIdTest()
        {
            // TODO unit test for the property 'CategoryId'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Remarks'
        /// </summary>
        [Fact]
        public void RemarksTest()
        {
            // TODO unit test for the property 'Remarks'
        }
        /// <summary>
        /// Test the property 'GalleryId'
        /// </summary>
        [Fact]
        public void GalleryIdTest()
        {
            // TODO unit test for the property 'GalleryId'
        }
        /// <summary>
        /// Test the property 'IsVat'
        /// </summary>
        [Fact]
        public void IsVatTest()
        {
            // TODO unit test for the property 'IsVat'
        }
        /// <summary>
        /// Test the property 'MainUnitId'
        /// </summary>
        [Fact]
        public void MainUnitIdTest()
        {
            // TODO unit test for the property 'MainUnitId'
        }
        /// <summary>
        /// Test the property 'SubUnitId'
        /// </summary>
        [Fact]
        public void SubUnitIdTest()
        {
            // TODO unit test for the property 'SubUnitId'
        }
        /// <summary>
        /// Test the property 'MainUnitAmount'
        /// </summary>
        [Fact]
        public void MainUnitAmountTest()
        {
            // TODO unit test for the property 'MainUnitAmount'
        }
        /// <summary>
        /// Test the property 'SubUnitAmount'
        /// </summary>
        [Fact]
        public void SubUnitAmountTest()
        {
            // TODO unit test for the property 'SubUnitAmount'
        }
        /// <summary>
        /// Test the property 'HasStock'
        /// </summary>
        [Fact]
        public void HasStockTest()
        {
            // TODO unit test for the property 'HasStock'
        }
        /// <summary>
        /// Test the property 'ProductCode'
        /// </summary>
        [Fact]
        public void ProductCodeTest()
        {
            // TODO unit test for the property 'ProductCode'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'BuyPrice'
        /// </summary>
        [Fact]
        public void BuyPriceTest()
        {
            // TODO unit test for the property 'BuyPrice'
        }
        /// <summary>
        /// Test the property 'BuyPriceWithVat'
        /// </summary>
        [Fact]
        public void BuyPriceWithVatTest()
        {
            // TODO unit test for the property 'BuyPriceWithVat'
        }
        /// <summary>
        /// Test the property 'IsBuyVat'
        /// </summary>
        [Fact]
        public void IsBuyVatTest()
        {
            // TODO unit test for the property 'IsBuyVat'
        }
        /// <summary>
        /// Test the property 'AllowOverSold'
        /// </summary>
        [Fact]
        public void AllowOverSoldTest()
        {
            // TODO unit test for the property 'AllowOverSold'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'IsDelete'
        /// </summary>
        [Fact]
        public void IsDeleteTest()
        {
            // TODO unit test for the property 'IsDelete'
        }
        /// <summary>
        /// Test the property 'VatRate'
        /// </summary>
        [Fact]
        public void VatRateTest()
        {
            // TODO unit test for the property 'VatRate'
        }
        /// <summary>
        /// Test the property 'BuyVatRate'
        /// </summary>
        [Fact]
        public void BuyVatRateTest()
        {
            // TODO unit test for the property 'BuyVatRate'
        }
        /// <summary>
        /// Test the property 'ResetTransactionId'
        /// </summary>
        [Fact]
        public void ResetTransactionIdTest()
        {
            // TODO unit test for the property 'ResetTransactionId'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Fact]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'ModifiedOn'
        /// </summary>
        [Fact]
        public void ModifiedOnTest()
        {
            // TODO unit test for the property 'ModifiedOn'
        }
        /// <summary>
        /// Test the property 'BroughtForwardOn'
        /// </summary>
        [Fact]
        public void BroughtForwardOnTest()
        {
            // TODO unit test for the property 'BroughtForwardOn'
        }
        /// <summary>
        /// Test the property 'BuyDescription'
        /// </summary>
        [Fact]
        public void BuyDescriptionTest()
        {
            // TODO unit test for the property 'BuyDescription'
        }
        /// <summary>
        /// Test the property 'BuyChartOfAccountId'
        /// </summary>
        [Fact]
        public void BuyChartOfAccountIdTest()
        {
            // TODO unit test for the property 'BuyChartOfAccountId'
        }
        /// <summary>
        /// Test the property 'SellChartOfAccountId'
        /// </summary>
        [Fact]
        public void SellChartOfAccountIdTest()
        {
            // TODO unit test for the property 'SellChartOfAccountId'
        }
        /// <summary>
        /// Test the property 'ProductNonInventoryType'
        /// </summary>
        [Fact]
        public void ProductNonInventoryTypeTest()
        {
            // TODO unit test for the property 'ProductNonInventoryType'
        }
        /// <summary>
        /// Test the property 'TransactionId'
        /// </summary>
        [Fact]
        public void TransactionIdTest()
        {
            // TODO unit test for the property 'TransactionId'
        }
        /// <summary>
        /// Test the property 'ProductMainUnit'
        /// </summary>
        [Fact]
        public void ProductMainUnitTest()
        {
            // TODO unit test for the property 'ProductMainUnit'
        }
        /// <summary>
        /// Test the property 'ProductSubUnit'
        /// </summary>
        [Fact]
        public void ProductSubUnitTest()
        {
            // TODO unit test for the property 'ProductSubUnit'
        }
        /// <summary>
        /// Test the property 'ProductCategory'
        /// </summary>
        [Fact]
        public void ProductCategoryTest()
        {
            // TODO unit test for the property 'ProductCategory'
        }
        /// <summary>
        /// Test the property 'IsMigrate'
        /// </summary>
        [Fact]
        public void IsMigrateTest()
        {
            // TODO unit test for the property 'IsMigrate'
        }

    }

}
