/*
 * FlowAccount Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ReceivableInvoiceAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReceivableInvoiceAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReceivableInvoiceAllOf
        //private ReceivableInvoiceAllOf instance;

        public ReceivableInvoiceAllOfTests()
        {
            // TODO uncomment below to create an instance of ReceivableInvoiceAllOf
            //instance = new ReceivableInvoiceAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReceivableInvoiceAllOf
        /// </summary>
        [Fact]
        public void ReceivableInvoiceAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReceivableInvoiceAllOf
            //Assert.IsType<ReceivableInvoiceAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ContactId'
        /// </summary>
        [Fact]
        public void ContactIdTest()
        {
            // TODO unit test for the property 'ContactId'
        }
        /// <summary>
        /// Test the property 'CompanyId'
        /// </summary>
        [Fact]
        public void CompanyIdTest()
        {
            // TODO unit test for the property 'CompanyId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Fact]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'ModifiedOn'
        /// </summary>
        [Fact]
        public void ModifiedOnTest()
        {
            // TODO unit test for the property 'ModifiedOn'
        }
        /// <summary>
        /// Test the property 'PublishedOn'
        /// </summary>
        [Fact]
        public void PublishedOnTest()
        {
            // TODO unit test for the property 'PublishedOn'
        }
        /// <summary>
        /// Test the property 'DocumentDate'
        /// </summary>
        [Fact]
        public void DocumentDateTest()
        {
            // TODO unit test for the property 'DocumentDate'
        }
        /// <summary>
        /// Test the property 'Published'
        /// </summary>
        [Fact]
        public void PublishedTest()
        {
            // TODO unit test for the property 'Published'
        }
        /// <summary>
        /// Test the property 'Approved'
        /// </summary>
        [Fact]
        public void ApprovedTest()
        {
            // TODO unit test for the property 'Approved'
        }
        /// <summary>
        /// Test the property 'ApprovedBy'
        /// </summary>
        [Fact]
        public void ApprovedByTest()
        {
            // TODO unit test for the property 'ApprovedBy'
        }
        /// <summary>
        /// Test the property 'ApprovedByClientId'
        /// </summary>
        [Fact]
        public void ApprovedByClientIdTest()
        {
            // TODO unit test for the property 'ApprovedByClientId'
        }
        /// <summary>
        /// Test the property 'ApprovedImageUrl'
        /// </summary>
        [Fact]
        public void ApprovedImageUrlTest()
        {
            // TODO unit test for the property 'ApprovedImageUrl'
        }
        /// <summary>
        /// Test the property 'DocumentSerial'
        /// </summary>
        [Fact]
        public void DocumentSerialTest()
        {
            // TODO unit test for the property 'DocumentSerial'
        }
        /// <summary>
        /// Test the property 'Remarks'
        /// </summary>
        [Fact]
        public void RemarksTest()
        {
            // TODO unit test for the property 'Remarks'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Fact]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }
        /// <summary>
        /// Test the property 'ExpectedDate'
        /// </summary>
        [Fact]
        public void ExpectedDateTest()
        {
            // TODO unit test for the property 'ExpectedDate'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Fact]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'DocumentId'
        /// </summary>
        [Fact]
        public void DocumentIdTest()
        {
            // TODO unit test for the property 'DocumentId'
        }
        /// <summary>
        /// Test the property 'IsDelete'
        /// </summary>
        [Fact]
        public void IsDeleteTest()
        {
            // TODO unit test for the property 'IsDelete'
        }
        /// <summary>
        /// Test the property 'VatRate'
        /// </summary>
        [Fact]
        public void VatRateTest()
        {
            // TODO unit test for the property 'VatRate'
        }
        /// <summary>
        /// Test the property 'InternalNotes'
        /// </summary>
        [Fact]
        public void InternalNotesTest()
        {
            // TODO unit test for the property 'InternalNotes'
        }
        /// <summary>
        /// Test the property 'GalleryId'
        /// </summary>
        [Fact]
        public void GalleryIdTest()
        {
            // TODO unit test for the property 'GalleryId'
        }
        /// <summary>
        /// Test the property 'IsVatInclusive'
        /// </summary>
        [Fact]
        public void IsVatInclusiveTest()
        {
            // TODO unit test for the property 'IsVatInclusive'
        }
        /// <summary>
        /// Test the property 'SalesId'
        /// </summary>
        [Fact]
        public void SalesIdTest()
        {
            // TODO unit test for the property 'SalesId'
        }
        /// <summary>
        /// Test the property 'SalesName'
        /// </summary>
        [Fact]
        public void SalesNameTest()
        {
            // TODO unit test for the property 'SalesName'
        }
        /// <summary>
        /// Test the property 'RoundingAdjustment'
        /// </summary>
        [Fact]
        public void RoundingAdjustmentTest()
        {
            // TODO unit test for the property 'RoundingAdjustment'
        }
        /// <summary>
        /// Test the property 'IsInlineDiscount'
        /// </summary>
        [Fact]
        public void IsInlineDiscountTest()
        {
            // TODO unit test for the property 'IsInlineDiscount'
        }
        /// <summary>
        /// Test the property 'IsInlineVat'
        /// </summary>
        [Fact]
        public void IsInlineVatTest()
        {
            // TODO unit test for the property 'IsInlineVat'
        }
        /// <summary>
        /// Test the property 'Tax'
        /// </summary>
        [Fact]
        public void TaxTest()
        {
            // TODO unit test for the property 'Tax'
        }
        /// <summary>
        /// Test the property 'DocumentSerialNoPrefix'
        /// </summary>
        [Fact]
        public void DocumentSerialNoPrefixTest()
        {
            // TODO unit test for the property 'DocumentSerialNoPrefix'
        }
        /// <summary>
        /// Test the property 'VatValue'
        /// </summary>
        [Fact]
        public void VatValueTest()
        {
            // TODO unit test for the property 'VatValue'
        }
        /// <summary>
        /// Test the property 'ResetTransactionId'
        /// </summary>
        [Fact]
        public void ResetTransactionIdTest()
        {
            // TODO unit test for the property 'ResetTransactionId'
        }
        /// <summary>
        /// Test the property 'Contact'
        /// </summary>
        [Fact]
        public void ContactTest()
        {
            // TODO unit test for the property 'Contact'
        }
        /// <summary>
        /// Test the property 'ApprovedByClient'
        /// </summary>
        [Fact]
        public void ApprovedByClientTest()
        {
            // TODO unit test for the property 'ApprovedByClient'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Fact]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'CreatedByUser'
        /// </summary>
        [Fact]
        public void CreatedByUserTest()
        {
            // TODO unit test for the property 'CreatedByUser'
        }
        /// <summary>
        /// Test the property 'ApprovedByUser'
        /// </summary>
        [Fact]
        public void ApprovedByUserTest()
        {
            // TODO unit test for the property 'ApprovedByUser'
        }
        /// <summary>
        /// Test the property 'Sales'
        /// </summary>
        [Fact]
        public void SalesTest()
        {
            // TODO unit test for the property 'Sales'
        }
        /// <summary>
        /// Test the property 'Gallery'
        /// </summary>
        [Fact]
        public void GalleryTest()
        {
            // TODO unit test for the property 'Gallery'
        }
        /// <summary>
        /// Test the property 'InlineVatValue'
        /// </summary>
        [Fact]
        public void InlineVatValueTest()
        {
            // TODO unit test for the property 'InlineVatValue'
        }
        /// <summary>
        /// Test the property 'InlineDiscountValue'
        /// </summary>
        [Fact]
        public void InlineDiscountValueTest()
        {
            // TODO unit test for the property 'InlineDiscountValue'
        }
        /// <summary>
        /// Test the property 'RuleCompileStatus'
        /// </summary>
        [Fact]
        public void RuleCompileStatusTest()
        {
            // TODO unit test for the property 'RuleCompileStatus'
        }
        /// <summary>
        /// Test the property 'RunningNumberType'
        /// </summary>
        [Fact]
        public void RunningNumberTypeTest()
        {
            // TODO unit test for the property 'RunningNumberType'
        }
        /// <summary>
        /// Test the property 'RunningModifiedOn'
        /// </summary>
        [Fact]
        public void RunningModifiedOnTest()
        {
            // TODO unit test for the property 'RunningModifiedOn'
        }
        /// <summary>
        /// Test the property 'ExemptAmount'
        /// </summary>
        [Fact]
        public void ExemptAmountTest()
        {
            // TODO unit test for the property 'ExemptAmount'
        }
        /// <summary>
        /// Test the property 'VatableAmount'
        /// </summary>
        [Fact]
        public void VatableAmountTest()
        {
            // TODO unit test for the property 'VatableAmount'
        }
        /// <summary>
        /// Test the property 'TotalAfterDiscount'
        /// </summary>
        [Fact]
        public void TotalAfterDiscountTest()
        {
            // TODO unit test for the property 'TotalAfterDiscount'
        }
        /// <summary>
        /// Test the property 'SubTotal'
        /// </summary>
        [Fact]
        public void SubTotalTest()
        {
            // TODO unit test for the property 'SubTotal'
        }
        /// <summary>
        /// Test the property 'DocumentReferences'
        /// </summary>
        [Fact]
        public void DocumentReferencesTest()
        {
            // TODO unit test for the property 'DocumentReferences'
        }
        /// <summary>
        /// Test the property 'ReferencedToMe'
        /// </summary>
        [Fact]
        public void ReferencedToMeTest()
        {
            // TODO unit test for the property 'ReferencedToMe'
        }
        /// <summary>
        /// Test the property 'ReferencedByMe'
        /// </summary>
        [Fact]
        public void ReferencedByMeTest()
        {
            // TODO unit test for the property 'ReferencedByMe'
        }
        /// <summary>
        /// Test the property 'StatusInt'
        /// </summary>
        [Fact]
        public void StatusIntTest()
        {
            // TODO unit test for the property 'StatusInt'
        }
        /// <summary>
        /// Test the property 'IsReCalculate'
        /// </summary>
        [Fact]
        public void IsReCalculateTest()
        {
            // TODO unit test for the property 'IsReCalculate'
        }
        /// <summary>
        /// Test the property 'PartialPaymentMethod'
        /// </summary>
        [Fact]
        public void PartialPaymentMethodTest()
        {
            // TODO unit test for the property 'PartialPaymentMethod'
        }
        /// <summary>
        /// Test the property 'VatAmount'
        /// </summary>
        [Fact]
        public void VatAmountTest()
        {
            // TODO unit test for the property 'VatAmount'
        }
        /// <summary>
        /// Test the property 'IsMigrate'
        /// </summary>
        [Fact]
        public void IsMigrateTest()
        {
            // TODO unit test for the property 'IsMigrate'
        }

    }

}
