<?php
/**
 * QuotationApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FlowAccount Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * QuotationApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class QuotationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for quotationChangeStatusByKey
     *
     * To change status by the document id and key.
     *
     */
    public function testQuotationChangeStatusByKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for quotationCreate
     *
     * To Create a document with SimpleDocument as the parameter.
     *
     */
    public function testQuotationCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for quotationCreate2
     *
     * To Create a document with InlineDocument as the parameter.
     *
     */
    public function testQuotationCreate2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for quotationCreatePartialManualPayall
     *
     * .
     *
     */
    public function testQuotationCreatePartialManualPayall()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for quotationDelete
     *
     * To delete the document given a list of documentids.
     *
     */
    public function testQuotationDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for quotationDetails
     *
     * To get details of a document.
     *
     */
    public function testQuotationDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for quotationEdit
     *
     * To Update a document with simpleDocument as the parameter.
     *
     */
    public function testQuotationEdit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for quotationEdit2
     *
     * To Update a document with inlineDocument as the parameter.
     *
     */
    public function testQuotationEdit2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for quotationIndex
     *
     * To query for documents..
     *
     */
    public function testQuotationIndex()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for quotationPartialManualCancel
     *
     * .
     *
     */
    public function testQuotationPartialManualCancel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for quotationReceivePayment
     *
     * To Accept payment with the paymentModel.
     *
     */
    public function testQuotationReceivePayment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
