<?php
/**
 * TaxInvoiceApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * FlowAccount Open API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TaxInvoiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TaxInvoiceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for taxInvoiceChangeStatusByKey
     *
     * To change status by the document id and key.
     *
     */
    public function testTaxInvoiceChangeStatusByKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for taxInvoiceCreate
     *
     * To Create a document with SimpleDocument as the parameter.
     *
     */
    public function testTaxInvoiceCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for taxInvoiceCreate2
     *
     * To Create a document with InlineDocument as the parameter.
     *
     */
    public function testTaxInvoiceCreate2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for taxInvoiceDelete
     *
     * To delete the document given a list of documentids.
     *
     */
    public function testTaxInvoiceDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for taxInvoiceDetails
     *
     * To get details of a document.
     *
     */
    public function testTaxInvoiceDetails()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for taxInvoiceEdit
     *
     * To Update a document with simpleDocument as the parameter.
     *
     */
    public function testTaxInvoiceEdit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for taxInvoiceEdit2
     *
     * To Update a document with inlineDocument as the parameter.
     *
     */
    public function testTaxInvoiceEdit2()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for taxInvoiceGetCumulativeDocumentReferenceList
     *
     * .
     *
     */
    public function testTaxInvoiceGetCumulativeDocumentReferenceList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for taxInvoiceIndex
     *
     * To query for documents..
     *
     */
    public function testTaxInvoiceIndex()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for taxInvoiceReceivePayment
     *
     * To Accept payment with the paymentModel.
     *
     */
    public function testTaxInvoiceReceivePayment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
